const CHANGE_LOGIN_TIP = 'CHANGE_LOGIN_TIP'   //改变登录的提示
const CHANGE_SIGN_TYPE = 'CHANGE_SIGN_TYPE'   //改变登录的类型
const CHANGE_TIP_TYPE = 'CHANGE_TIP_TYPE'     //改变提示的类型

export {
    CHANGE_LOGIN_TIP,
    CHANGE_SIGN_TYPE,
    CHANGE_TIP_TYPE
}