const CHANGE_TYPE = 'CHANGE_TYPE'   //改变登录的状态
const LOGIN = 'LOGIN'
const REGISTER = 'REGISTER'
const FETCH_USER_INFO = 'FETCH_USER_INFO'
const LOGOUT = 'LOGOUT'

export {
    CHANGE_TYPE,
    LOGIN,
    REGISTER,
    FETCH_USER_INFO,
    LOGOUT
}